# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Example Mouse Emulation"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["lpgalaxy_blank_slate"]'
      mapping: '["extended_thumbs"]'
      clipboard: '["mac"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
      branches: '["zmkfirmware/zmk/main"]'
